/*************************************************************************************************************
 * This class will have all the constants needed at various places
 *
 *  @author – Bfl Dev – garima.kour@theblueflamelabs.com
 ***************************************************************************************************************/
@SuppressWarnings('PMD.classnamingconventions')
public class Bfl_Constant {
    public static final String CONTACT_B2C_RECORD = 'B2C_Consumer';
    public static final Integer MONTH_DIFFERENCE = 36;
    public static final Integer BATCH_SIZE = 200;

    //Class BFL_CaseTriggerHandler
    public static final String EMAIL = 'Email';
    public static final String WEB = 'Web';
    public static final String BFL_B2C_CUSTOMER_OF = 'BFL B2C Customer of ';
    public static final String BFL_IN = ' in ';
    public static final String SENDER_DISPLAY_NAME = 'Company Support';
    public static final String NO_REPLY_COMPANY = 'no-reply@company.com';
    public static final String CASE_OBJECT = 'Case';
    public static final String LANGUAGE_API = 'Language__c';
    //Sales Report
    public static final String SH_BRAND_FULL = 'Silhouette';
    public static final String MONTH_SEPARATOR = '_M';
    public static final String CALENDAR_YEAR_QUARTER = 'Calendar Year Quarter';
    public static final String FISCAL_YEAR = '_FY';
    public static final String FINANCIAL_YEAR_QUARTER = 'Financial Year Quarter';
    public static final String MET_WITH_CONTACT_REALIZATION = 'Met with Contact';
    public static final String SH_SEGMENT_QUESTIONABLE = 'Questionable';
    public static final String ADMINISTRATIVE_REALIZATION = 'Administrative';
    public static final String SH_BRAND_SHORT = 'SH';
    public static final String RECORD_TYPE_REF_AUDIT_ITEM = 'Reference Audit Item';
    public static final String REF_ATTR2_NAME_SUN = 'Sun';
    public static final String REF_ATTR2_NAME_SH_NOT_DISPLAYED = 'SH_Not Displayed';
    public static final String IS_FC = 'is FC';
    public static final String NO_FC = 'no FC';
    public static final String EE_BRAND_SHORT = 'EE';
    public static final String NO_FOCUS_COLLECTION = 'No Focus Collection';
    public static final String QUARTER_ONE = 'Quarter 1';
    public static final String QUARTER_TWO = 'Quarter 2';
    public static final String QUARTER_THREE = 'Quarter 3';
    public static final String QUARTER_FOUR = 'Quarter 4';
    public static final String SALES_REPORT_OBJECT = 'Sales_Report__c';
    public static final String OTHER = 'Other';
    public static final String FY_SEPERATOR = '_FY_';
    public static final String UNDERSCORE = '_';
    public static final String Q_ALPHA = '/Q';
    public static final String PLANNED_QUICK_PITCHER_CALL_TYPE = 'Planned (Quick)';
    public static final String STAGE_ACCOUNT = 'Account';
    public static final String STAGE_PROSPECT = 'Prospect';
    public static final String SH_ACP_STATUS_NO_ACP = '10';
    public static final String SH_ACP_STATUS_IN_PROGRESS = '20';
    public static final String SH_ACP_STATUS_AGREEMENT_SENT = '60';
    public static final String SH_ACC_STATUS_INACTIVE = 'inactive';
    public static final String TEST_ACCOUNT_NAME = 'TestAccount';
    public static final String TEST_USER_NAME = 'Testuser';
    public static final String ORDER_LOCK_STATUS_LOCKED = 'Locked';
    public static final String GROUPE = '_Group';
    public static final String GROUP_EXCL_US = '_Group excl. US';
    public static final String VISIT_TYPE_INITIAL_VISIT = 'Initial Visit';
    public static final String VISIT_TYPE_VIRTUAL_MEETING = 'Virtual Meeting';
    public static final String VISIT_TYPE_OTHERS = 'Others';
    public static final String VISIT_TYPE_SALES_VISIT = 'Sales Visit';
    public static final String VISIT_TYPE_TRAINING_VISIT = 'Training Visit';
    public static final String VISIT_TYPE_ACC_PLAN_MEETING = 'Account Plan Meeting';
    public static final String VISIT_TYPE_STYLE_DAY = 'Style Day';
    public static final String VISIT_TYPE_SIL_AND_FRIENDS = 'Silhouette & Friends';
    public static final String VISIT_TYPE_TRUNK_SHOW = 'Trunk Show (US)';
    public static final String VISIT_TYPE_HOME_OFFICE = 'Home Office';
    public static final String VISIT_TYPE_PROSPECT_IN_VISIT = 'Prospect Initial Visit';
    public static final String VISIT_TYPE_MERCHANT_AND_PROMOTION = 'Merchandising & Promotion';
    public static final String NOT_POSSIBLE = 'Not Possible';
    public static final String NB_BRAND_FULL = 'NEUBAU';
    public static final String EE_BRAND_FULL = 'evil eye';
    public static final String NB_BRAND_SHORT = 'NB';
    public static final String SUCCESS = 'Success';
    public static final String STAGE_PROSPECT_B2B = 'Prospect_B2B'; //BS-304
    public static final String PROSPECT_RECORDTYPE_DEVELOPERNAME = 'k_Prospect'; //BS-304
    public static final String ACCOUNT_RECORDTYPE_DEVELOPERNAME = 'k_Account'; //BS-304
    public static final String SIL_INTERNATIONAL_HQ_ROLE = 'k_Sil_International_HQ'; //BS-157
    public static final String COMMERCE_USER_PROFILE_NAME = 'B2B Commerce User Silhouette'; //BS-157
    public static final String B2B_ORDER_RECORDTYPE_DEVELOPERNAME = 'B2B_Order'; //BS-424
    public static final String B2C_ORDER_RECORDTYPE_DEVELOPERNAME = 'B2C_Order'; //BS-424
    public static final String CUSTOMER_REFERENCE_VALUE = 'Customer Reference'; //BS-204
    public static final String ENTERED_BY_VALUE = 'Entered By'; //BS-204
    public static final String B2B_ORDER_RECORDTYPE = 'B2B Order'; //BS-303
    public static final String ORDER_STATUS_DRAFT = 'Draft'; //BS-303
    public static final String ORDER_STATUS_ORDER_SENT = '10'; //BS-303
    public static final String ORDER_SOURCE_B2B_SHOP = 'Partner Portal'; //Updated as Part of BS-746
    public static final String CART_STATUS_CLOSED = 'Closed'; //BS-303
    public static final String COLLECTION_FRAME = 'Collection/Frame'; //SC-320
    public static final String REF_ATTR2_SUN = 'SUN'; //SC-320
    public static final String COUNTRY_CODE_PO = 'POPO'; //SC-320
    public static final String US = 'USUS'; //SC-320
}
