/*************************************************************************************************************
 * This class will have all the constants needed at various places for D2C
 *
 *  @author – Shrihari Kendre
 ***************************************************************************************************************/
public with sharing class D2C_Constants {
    public static final String MODEL_IMAGE = 'Model Image'; //NBD2C-39
    public static final String PRODUCT_IMAGE = 'Product Image'; //NBD2C-29
    public static final String D2C_VALUE = 'D2C'; //NBD2C-29
    public static final String PREMIUM = 'Premium'; //NBD2C-65
    public static final String LIGHTHOUSE = 'LightHouse'; //NBD2C-65
    public static final String ACCOUNT = 'Account'; //NBD2C-65
    public static final String NEUBAU = 'Neubau'; //NBD2C-82
    public static final String FIRST_NAME = 'firstname'; //NBD2C-32
    public static final String LAST_NAME = 'lastname'; //NBD2C-32
    public static final String EMAIL = 'email'; //NBD2C-32
    public static final String SALUTATION = 'salutation'; //NBD2C-32
    public static final String LANGUAGE = 'language'; //NBD2C-32
    public static final String COUNTRY = 'country'; //NBD2C-32
    public static final String B2C_CONSUMER_RECORD_TYPE = 'B2C_Consumer'; //NBD2C-32
    public static final String ACCOUNT_OBJECT = 'Account'; //NBD2C-32
    public static final String PACKAGING_IMAGE = 'Packaging Image'; //NBD2C-32
    public static final String SILHOUETTE = 'Silhouette'; //DVM21-48
    public static final String SH = 'SH'; //DVM21-48
}
